# Generated by Django 5.2.8 on 2025-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
